name: tmi_jobs_search
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  auth_repo:
   path: local_packages/auth_repo
  graphql_flutter: ^5.1.2
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  go_router: ^12.0.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  formz: ^0.6.1
  email_validator: ^2.1.17
# dependency_overrides:
#   graphql_flutter: 5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
 